# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OnNB_uvWFvr9r0ofXvpQlHDj7hT2Xs1X

# Read Tabular Data using Pandas

## Bad method
"""

with open('weather_data.csv') as f:
    data = f.read()

data

"""## Good method"""

import pandas as pd

df = pd.read_csv('weather_data.csv')

df = pd.read_excel('weather_data.xlsx')

df

print(df)

print(type(df))

"""## Pandas Dataframe"""

df.head(3)

df.tail(3)

df.shape

df.dtypes

df.describe()

"""## Pandas Series"""

tmp = df['temp']

tmp

print(type(tmp))

tmp.describe()

tmp.max()

tmp.min()

tmp.mean()

conditions = df['condition']

conditions.describe()

"""## Conditional Indexing"""

df['condition'] == 'Sunny'

df[df['condition'] == 'Sunny']

df[df['temp'] == df['temp'].max()]

df[df['temp'] >= df['temp'].mean()]

